# Generated by Django 3.2.9 on 2021-11-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211115_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='context',
            field=models.CharField(max_length=5000),
        ),
    ]
