# Generated by Django 3.2.9 on 2021-11-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20211115_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='context',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
