# Generated by Django 3.2.9 on 2021-11-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_data_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='mensaje_usuario',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='respuesta_bot',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
