<<<<<<< HEAD
# Generated by Django 3.2.9 on 2021-11-16 18:13
=======
# Generated by Django 3.2.9 on 2021-11-18 20:13
>>>>>>> 76d66ffa24f1dcff20153c03a0cc21c147908fcf

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20211115_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Conversación', 'verbose_name_plural': 'Conversaciones'},
        ),
    ]
